spring.application.name=ushi_backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ushi_backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:2611}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=letrongkhanh26112004@gmail.com
spring.mail.password=moxx rzll ykpw fvcr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.access-token-secret=U29tZVN1cGVyU2VjdXJlQWNjZXNzVG9rZW5LZXlGb3JVc2hpQmFja2VuZDIwMjY=
app.jwt.refresh-token-secret=U29tZVN1cGVyU2VjdXJlUmVmcmVzaFRva2VuS2V5Rm9yVXNoaUJhY2tlbmQyMDI2
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000
app.registration-otp.expiration-minutes=5
app.registration-otp.resend-cooldown-seconds=60
